spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    open-in-view: true
  datasource:
    url: jdbc:mysql://localhost:3306/Dawid?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: Dawid
    password: kotnaplocie1
server:
  port: 80
